export const AgriData: Fulldata = {
  data: [
    {
      type: "executing",
      id: "AGRI_001",
      name: "Alex LEE",
      time: "Mon,10 Apr, 10:40PM",
      download: "agri_001",
      orders: [
        {
          id: 1,
          item: "seeds/seedlings",
          img: "./images/pesticides.png",
          description: "Chilli Sakat 651 (1500 seeds)",
          quantity: 56,
        },
        {
          id: 2,
          item: "Nutrients/Fertilizers",
          img: "./images/ferti.jpg",
          description: "Acme Brand Fert A/B Set -50Kg",
          quantity: 20,
        },
        {
          id: 3,
          item: "Pesticides",
          img: "./images/pesticides.png",
          description: "Vailants ME 30ml",
          quantity: 30,
        },
        {
          id: 4,
          item: "Growing Medium",
          img: "./images/ferti.jpg",
          description: "Acme Brand Cocopeat 30g",
          quantity: 40,
        },
        {
          id: 5,
          item: "Growing Medium",
          img: "./images/pesticides.png",
          description: "Acem Brand CocoHusk 50g",
          quantity: 50,
        },
      ],
    },
    {
      type: "executing",
      id: "AGRI_002",
      name: "Abhishek",
      time: "Fri,14 Apr, 10:00PM",
      download: "agri_002",
      orders: [
        {
          id: 1,
          item: "seeds/seedlings",
          img: "./images/pesticides.png",
          description: "Chilli Sakat 651 (1500 seeds)",
          quantity: 56,
        },
        {
          id: 2,
          item: "Nutrients/Fertilizers",
          img: "./images/ferti.png",
          description: "Acme Brand Fert A/B Set -50Kg",
          quantity: 20,
        },
        {
          id: 3,
          item: "Pesticides",
          img: "./images/pesticides.png",
          description: "Vailants ME 30ml",
          quantity: 30,
        },
        {
          id: 4,
          item: "Growing Medium",
          img: "./images/ferti.jpg",
          description: "Acme Brand Cocopeat 30g",
          quantity: 40,
        },
        {
          id: 5,
          item: "Growing Medium",
          img: "./images/pesticides.png",
          description: "Acem Brand CocoHusk 50g",
          quantity: 50,
        },
      ],
    },
    {
      type: "executing",
      id: "AGRI_003",
      name: "Abhishek Dahiya",
      time: "Sun,16 Apr, 10:00PM",
      download: "agri_003",
      orders: [
        {
          id: 1,
          item: "seeds/seedlings",
          img: "./images/pesticides.png",
          description: "Chilli Sakat 651 (1500 seeds)",
          quantity: 56,
        },
        {
          id: 2,
          item: "Nutrients/Fertilizers",
          img: "./images/ferti.jpg",
          description: "Acme Brand Fert A/B Set -50Kg",
          quantity: 20,
        },
        {
          id: 3,
          item: "Pesticides",
          img: "./images/pesticides.png",
          description: "Vailants ME 30ml",
          quantity: 30,
        },
        {
          id: 4,
          item: "Growing Medium",
          img: "./images/ferti.jpg",
          description: "Acme Brand Cocopeat 30g",
          quantity: 40,
        },
        {
          id: 5,
          item: "Growing Medium",
          img: "./images/pesticides.png",
          description: "Acem Brand CocoHusk 50g",
          quantity: 50,
        },
      ],
    },
  ],
};
